import type { Product, Order, ProductCategory } from './types';

export const products: Product[] = [
  {
    id: 'hp-pavilion-15',
    name: 'HP Pavilion 15 i5 11th Gen',
    category: 'Laptops',
    subcategory: 'Business',
    brand: 'HP',
    price: 74999,
    currency: 'KES',
    stock: 12,
    description: 'Powerful laptop with 11th Gen Intel Core i5, 8GB RAM, 512GB SSD for work and entertainment.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: true,
    rating: 4.6,
    promoTag: 'Top Rated'
  },
  {
    id: 'mx-master-3s',
    name: 'Logitech MX Master 3S Wireless Mouse',
    category: 'Mice',
    brand: 'Logitech',
    price: 12800,
    currency: 'KES',
    stock: 25,
    description: 'Advanced wireless mouse with ergonomic design, quiet clicks, and 8K DPI sensor for precision.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: true,
    rating: 4.9,
  },
  {
    id: 'acer-nitro-5',
    name: 'Acer Nitro 5 Gaming Laptop Ryzen 5',
    category: 'Laptops',
    subcategory: 'Gaming',
    brand: 'Acer',
    price: 109999,
    currency: 'KES',
    stock: 7,
    description: 'Dominate the game with an AMD Ryzen 5 CPU and NVIDIA GeForce RTX 30 Series GPU.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: true,
    rating: 4.7,
    promoTag: '15% OFF'
  },
  {
    id: 'aoc-24-monitor',
    name: 'AOC 24" Full HD LED Monitor',
    category: 'Monitors',
    brand: 'AOC',
    price: 17999,
    currency: 'KES',
    stock: 14,
    description: '24-inch Full HD monitor with vibrant colors and slim design, perfect for any workspace.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: false,
    rating: 4.5,
  },
  {
    id: 'redragon-k552',
    name: 'Redragon K552 Mechanical Gaming Keyboard',
    category: 'Keyboards',
    brand: 'Redragon',
    price: 5499,
    currency: 'KES',
    stock: 20,
    description: 'Compact mechanical keyboard with custom switches, RGB backlighting, and durable construction.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: true,
    rating: 4.4,
  },
  {
    id: 'seagate-1tb-hdd',
    name: 'Seagate 1TB External HDD USB 3.0',
    category: 'Storage Drives',
    subcategory: 'External',
    brand: 'Seagate',
    price: 5299,
    currency: 'KES',
    stock: 33,
    description: 'Portable and reliable storage for your files, with fast USB 3.0 connectivity.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: false,
    rating: 4.6,
  },
  {
    id: 'tplink-webcam',
    name: 'TP-Link 1080p USB Webcam',
    category: 'Webcams',
    brand: 'TP-Link',
    price: 3199,
    currency: 'KES',
    stock: 18,
    description: 'High-definition 1080p video for clear streaming and video calls, with built-in microphone.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: false,
    rating: 4.2,
  },
  {
    id: 'rtx-3060-ti',
    name: 'NVIDIA RTX 3060 Ti Graphics Card',
    category: 'Graphic Cards',
    brand: 'NVIDIA',
    price: 82000,
    currency: 'KES',
    stock: 4,
    description: 'Experience incredible performance with Ampere—NVIDIA’s 2nd gen RTX architecture.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: true,
    rating: 4.8,
  },
  {
    id: 'intel-i7-12700f',
    name: 'Intel Core i7-12700F',
    category: 'Processors',
    brand: 'Intel',
    price: 53500,
    currency: 'KES',
    stock: 6,
    description: '12th Gen Intel Core i7 processor with Performance-cores and Efficient-cores for amazing performance.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: true,
    rating: 4.9,
  },
  {
    id: 'corsair-vengeance-16gb',
    name: 'Corsair Vengeance 16GB DDR4 3200MHz',
    category: 'RAM Modules',
    brand: 'Corsair',
    price: 8499,
    currency: 'KES',
    stock: 10,
    description: 'High-performance DDR4 memory optimized for Intel & AMD motherboards, with stylish heat spreader.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: false,
    rating: 4.7,
  },
  {
    id: 'dell-ultrasharp-27',
    name: 'Dell UltraSharp 27" 4K Monitor',
    category: 'Monitors',
    brand: 'Dell',
    price: 58000,
    currency: 'KES',
    stock: 9,
    description: 'Stunning 4K resolution with superb color accuracy, ideal for creative professionals.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: true,
    rating: 4.8,
  },
  {
    id: 'samsung-980-pro-1tb',
    name: 'Samsung 980 Pro 1TB NVMe SSD',
    category: 'Storage Drives',
    subcategory: 'Internal',
    brand: 'Samsung',
    price: 17500,
    currency: 'KES',
    stock: 15,
    description: 'Next-level SSD performance with read speeds up to 7,000 MB/s for pro-level gaming and apps.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: true,
    rating: 4.9,
    promoTag: 'Ships in 24h'
  },
  {
    id: 'jbl-quantum-400',
    name: 'JBL Quantum 400 Gaming Headset',
    category: 'Headphones',
    brand: 'JBL',
    price: 8500,
    currency: 'KES',
    stock: 22,
    description: 'Immersive gaming headset with JBL QuantumSOUND Signature and flip-up boom mic.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: false,
    rating: 4.5,
  },
  {
    id: 'ryzen-7-5800x',
    name: 'AMD Ryzen 7 5800X Processor',
    category: 'Processors',
    brand: 'AMD',
    price: 42000,
    currency: 'KES',
    stock: 11,
    description: '8 Cores and 16 processing threads, based on AMD "Zen 3" architecture.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: false,
    rating: 4.8,
  },
  {
    id: 'asus-tuf-b550-plus',
    name: 'ASUS TUF Gaming B550-PLUS Motherboard',
    category: 'Motherboards',
    brand: 'ASUS',
    price: 21000,
    currency: 'KES',
    stock: 8,
    description: 'AMD B550 (Ryzen AM4) ATX gaming motherboard with PCIe 4.0, dual M.2, 2.5Gb Ethernet.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: false,
    rating: 4.7,
  },
  {
    id: 'lenovo-ideapad-3',
    name: 'Lenovo IdeaPad 3 Celeron',
    category: 'Laptops',
    subcategory: 'Budget',
    brand: 'Lenovo',
    price: 32500,
    currency: 'KES',
    stock: 20,
    description: 'Entry-level laptop for everyday tasks with a 15.6" HD display and long battery life.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: false,
    rating: 4.1,
  },
  {
    id: 'hp-elite-desk-mini',
    name: 'HP EliteDesk Mini G5',
    category: 'Desktops',
    brand: 'HP',
    price: 85000,
    currency: 'KES',
    stock: 5,
    description: 'Ultra-compact business desktop with powerful performance and robust security features.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: true,
    rating: 4.6,
  },
  {
    id: 'corsair-cv650',
    name: 'Corsair CV650 Power Supply',
    category: 'Power Supplies',
    brand: 'Corsair',
    price: 7500,
    currency: 'KES',
    stock: 16,
    description: '650 Watt 80 Plus Bronze certified PSU for reliable and efficient power delivery.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: false,
    rating: 4.5,
  },
  {
    id: 'cooler-master-hyper-212',
    name: 'Cooler Master Hyper 212 CPU Cooler',
    category: 'Coolers/Fans',
    brand: 'Cooler Master',
    price: 4500,
    currency: 'KES',
    stock: 25,
    description: 'Legendary air cooler with exceptional cooling performance and quiet operation.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: false,
    rating: 4.7,
  },
  {
    id: 'logitech-g203',
    name: 'Logitech G203 Gaming Mouse',
    category: 'Mice',
    brand: 'Logitech',
    price: 3500,
    currency: 'KES',
    stock: 30,
    description: 'Gaming-grade sensor and vibrant LIGHTSYNC RGB lighting in a classic design.',
    imageUrl: 'https://placehold.co/600x600.png',
    featured: false,
    rating: 4.3,
  },
];


export const orders: Order[] = [
  {
    id: 'ZOV-84920',
    productName: 'HP Pavilion 15 i5 11th Gen',
    status: 'Processing',
    timestamp: '2024-07-28 14:30:15',
    total: 74999,
    user: 'client@zizo.net'
  },
  {
    id: 'ZOV-84919',
    productName: 'Acer Nitro 5 Gaming Laptop Ryzen 5',
    status: 'Delivered',
    timestamp: '2024-07-25 10:05:42',
    total: 109999,
    user: 'client@zizo.net'
  },
  {
    id: 'ZOV-84918',
    productName: 'Logitech MX Master 3S Wireless Mouse',
    status: 'Delivered',
    timestamp: '2024-07-24 18:22:01',
    total: 12800,
    user: 'vendor@zizo.net' // To show vendors can also be clients
  },
   {
    id: 'ZOV-84917',
    productName: 'NVIDIA RTX 3060 Ti Graphics Card',
    status: 'Failed',
    timestamp: '2024-07-23 09:15:33',
    total: 82000,
    user: 'client@zizo.net'
  },
];

export const categoryData: { name: ProductCategory; href: string; subcategories?: string[] }[] = [
    { name: 'Laptops', href: '/shop?category=Laptops', subcategories: ['Gaming', 'Ultrabooks', 'Business', 'Budget'] },
    { name: 'Desktops', href: '/shop?category=Desktops' },
    { name: 'Monitors', href: '/shop?category=Monitors' },
    { name: 'Keyboards', href: '/shop?category=Keyboards' },
    { name: 'Mice', href: '/shop?category=Mice' },
    { name: 'Headphones', href: '/shop?category=Headphones' },
    { name: 'Webcams', href: '/shop?category=Webcams' },
    { name: 'Storage Drives', href: '/shop?category=Storage Drives', subcategories: ['Internal', 'External'] },
    { name: 'Graphic Cards', href: '/shop?category=Graphic Cards' },
    { name: 'Processors', href: '/shop?category=Processors' },
    { name: 'RAM Modules', href: '/shop?category=RAM Modules' },
    { name: 'Motherboards', href: '/shop?category=Motherboards' },
    { name: 'Power Supplies', href: '/shop?category=Power Supplies' },
    { name: 'Coolers/Fans', href: '/shop?category=Coolers/Fans' },
];

export const categories = categoryData.map(c => ({ name: c.name, href: c.href }));
